export const RECEIVE_SESSIONS_REDIRECT_URL = 'RECEIVE_SESSIONS_REDIRECT_URL'
export const RESET_SESSIONS_REDIRECT_URL = 'RESET_SESSIONS_REDIRECT_URL'
export const FETCH_SESSIONS_AUTHENTICATE = 'FETCH_SESSIONS_AUTHENTICATE'
export const RECEIVE_SESSIONS_AUTHENTICATE = 'RECEIVE_SESSIONS_AUTHENTICATE'
export const REMOVE_SESSIONS_AUTHENTICATE = 'REMOVE_SESSIONS_AUTHENTICATE'

export const FETCH_TODO = 'FETCH_TODO'
export const RECEIVE_TODO = 'RECEIVE_TOD'
export const FETCH_TODOS = 'FETCH_TODO'
export const RECEIVE_TODOS = 'RECEIVE_TODO'

export const RECEIVE_PROGRESS_LINEAR = 'RECEIVE_PROGRESS_LINEAR'
export const REMOVE_PROGRESS_LINEAR = 'REMOVE_PROGRESS_LINEAR'
export const UPDATE_PROGRESS_LINEAR = 'UPDATE_PROGRESS_LINEAR'

export const FETCH_LETTERS_CREDIT = 'FETCH_LETTERS_CREDIT'

export const FETCH_TESTIMONIALS = 'FETCH_TESTIMONIALS'
export const RECEIVE_TESTIMONIALS = 'RECEIVE_TESTIMONIALS'

export const FETCH_BANNERS = 'FETCH_BANNERS'
export const RECEIVE_BANNERS = 'RECEIVE_BANNERS'
