export const RECEIVE_SESSIONS_REDIRECT_URL = 'RECEIVE_SESSIONS_REDIRECT_URL'
export const RESET_SESSIONS_REDIRECT_URL = 'RESET_SESSIONS_REDIRECT_URL'
export const FETCH_SESSIONS_AUTHENTICATE = 'FETCH_SESSIONS_AUTHENTICATE'
export const RECEIVE_SESSIONS_AUTHENTICATE = 'RECEIVE_SESSIONS_AUTHENTICATE'
export const REMOVE_SESSIONS_AUTHENTICATE = 'REMOVE_SESSIONS_AUTHENTICATE'

export const FETCH_TODO = 'FETCH_TODO'
export const RECEIVE_TODO = 'RECEIVE_TOD'
export const FETCH_TODOS = 'FETCH_TODO'
export const RECEIVE_TODOS = 'RECEIVE_TODO'

export const RECEIVE_PROGRESS_LINEAR = 'RECEIVE_PROGRESS_LINEAR'
export const REMOVE_PROGRESS_LINEAR = 'REMOVE_PROGRESS_LINEAR'
export const UPDATE_PROGRESS_LINEAR = 'UPDATE_PROGRESS_LINEAR'

export const FETCH_LETTERS_CREDIT_HOME = 'FETCH_LETTERS_CREDIT_HOME'
export const RECEIVE_LETTERS_CREDIT_HOME = 'RECEIVE_LETTERS_CREDIT_HOME'
export const FETCH_LETTER_CREDIT_BY_ID_RESULT = 'FETCH_LETTER_CREDIT_BY_ID_RESULT'
export const RECEIVE_LETTER_CREDIT_BY_ID_RESULT = 'RECEIVE_LETTER_CREDIT_BY_ID_RESULT'
export const FETCH_LETTERS_CREDIT_RESULT = 'FETCH_LETTERS_CREDIT_RESULT'
export const RECEIVE_LETTERS_CREDIT_RESULT = 'RECEIVE_LETTERS_CREDIT_RESULT'

export const FETCH_TESTIMONIALS = 'FETCH_TESTIMONIALS'
export const RECEIVE_TESTIMONIALS = 'RECEIVE_TESTIMONIALS'

export const FETCH_BANNERS = 'FETCH_BANNERS'
export const RECEIVE_BANNERS = 'RECEIVE_BANNERS'

export const FETCH_VEHICLES_HOME = 'FETCH_VEHICLES_HOME'
export const RECEIVE_VEHICLES_HOME = 'RECEIVE_VEHICLES_HOME'
export const FETCH_VEHICLES_BY_IDS_RESULT = 'FETCH_VEHICLES_BY_IDS_RESULT'
export const RECEIVE_VEHICLES_BY_IDS_RESULT = 'RECEIVE_VEHICLES_BY_IDS_RESULT'

export const FETCH_INTERESTED_RESULT = 'FETCH_INTERESTED_RESULT'
export const RECEIVE_INTERESTED_RESULT = 'RECEIVE_INTERESTED_RESULT'
export const RECEIVE_FORM_RESULT = 'RECEIVE_FORM_RESULT'