export const RECEIVE_SESSIONS_REDIRECT_URL = 'RECEIVE_SESSIONS_REDIRECT_URL'
export const RESET_SESSIONS_REDIRECT_URL = 'RESET_SESSIONS_REDIRECT_URL'
export const FETCH_SESSIONS_AUTHENTICATE = 'FETCH_SESSIONS_AUTHENTICATE'
export const RECEIVE_SESSIONS_AUTHENTICATE = 'RECEIVE_SESSIONS_AUTHENTICATE'

export const FETCH_TODO = 'FETCH_TODO'
export const RECEIVE_TODO = 'RECEIVE_TOD'
export const FETCH_TODOS = 'FETCH_TODO'
export const RECEIVE_TODOS = 'RECEIVE_TODO'